import React, { useState, useEffect } from 'react';

const Dashboard = ({ onReset, results, initialCode }) => {
    const [selectedVuln, setSelectedVuln] = useState(null);
    const [currentCode, setCurrentCode] = useState(initialCode || '');
    const [liveResults, setLiveResults] = useState(results);
    const [isFixing, setIsFixing] = useState(false);
    const [fixTarget, setFixTarget] = useState(null);

    // Analysis Logic (Reusable)
    const analyzeCode = (code) => {
        const vulnerable = [];
        const lines = code.split('\n');
        const findMatches = (regex, name) => {
            lines.forEach((line, index) => {
                if (regex.test(line)) {
                    vulnerable.push({
                        name,
                        line: index + 1,
                        content: line.trim(),
                        recommendation: name === 'RSA-2048' ? 'Migrate to CRYSTALS-Kyber' :
                            (name === 'ECC-P256' ? 'Migrate to CRYSTALS-Dilithium' : 'Upgrade to PQC alternative')
                    });
                }
            });
        };

        findMatches(/rsa/i, 'RSA-2048');
        findMatches(/sha1|md5/i, 'Legacy Hash (MD5/SHA1)');
        findMatches(/aes-128|des|3des/i, 'DES/AES-128');
        findMatches(/p256|secp256k1|elliptic/i, 'ECC-P256');
        findMatches(/diffie[- ]?hellman/i, 'Diffie-Hellman');

        const uniqueAlgs = [...new Set(vulnerable.map(v => v.name))];
        const riskBoost = uniqueAlgs.length * 15;
        const riskScore = Math.min(95, 30 + riskBoost + Math.floor(Math.random() * 10));
        const readinessScore = Math.max(10, 90 - (uniqueAlgs.length * 12));

        return {
            riskScore: vulnerable.length === 0 ? 5 : riskScore,
            readinessScore: vulnerable.length === 0 ? 98 : readinessScore,
            vulnerable: vulnerable.length > 0 ? vulnerable : [{ name: 'No standard vulnerabilities detected', line: '-', content: 'N/A' }],
            threats: vulnerable.length === 0 ? 0 : Math.max(1, vulnerable.length * 3 + Math.floor(Math.random() * 5)),
            mitigationTime: (uniqueAlgs.length * 1.5).toFixed(1)
        };
    };

    // Re-run analysis when code changes
    useEffect(() => {
        if (currentCode) {
            const newResults = analyzeCode(currentCode);
            setLiveResults(newResults);
        }
    }, [currentCode]);

    const data = liveResults || results;
    const riskLevel = data.riskScore > 70 ? 'HIGH' : (data.riskScore > 40 ? 'MEDIUM' : 'LOW');
    const riskColor = riskLevel === 'HIGH' ? 'var(--accent-danger)' : (riskLevel === 'MEDIUM' ? 'var(--accent-warning)' : 'var(--accent-success)');

    const pqcSolutions = {
        'CRYSTALS-Kyber': {
            desc: 'Post-Quantum Key Encapsulation Mechanism',
            usage: '// Replace RSA/DH with CRYSTALS-Kyber\nconst kyber = require("@qsafe/kyber");\nconst { publicKey, secretKey } = kyber.keyPair();\nconst ciphertext = kyber.encrypt(publicKey);'
        },
        'CRYSTALS-Dilithium': {
            desc: 'Post-Quantum Digital Signature Algorithm',
            usage: '// Replace ECC/RSA signatures with CRYSTALS-Dilithium\nconst dilithium = require("@qsafe/dilithium");\nconst { pk, sk } = dilithium.keyPair();\nconst signature = dilithium.sign(message, sk);'
        },
        'SPHINCS+': {
            desc: 'Stateless Hash-Based Digital Signature',
            usage: '// For long-term certificate validation\nconst sphincs = require("@qsafe/sphincs");\nconst signature = sphincs.sign(data, privateKey);'
        }
    };

    const handleDownload = () => {
        const reportContent = `
============================================================
POST-QUANTUM CRYPTOGRAPHY READINESS AUDIT REPORT
Generated by: QSafe Security Engine v4.2
Date: ${new Date().toLocaleString()}
============================================================
1. EXECUTIVE SUMMARY
Quantum Risk Level: ${riskLevel} (${data.riskScore}%)
Migration Readiness Score: ${data.readinessScore}%
Detected Threat Vectors: ${data.threats}
============================================================
        `;
        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `QSafe_Report.txt`;
        link.click();
    };

    return (
        <div className="container" style={{ padding: 'var(--spacing-lg) 0' }}>
            {/* Remediation Terminal Modal */}
            {isFixing && (
                <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(15, 23, 42, 0.95)', zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div className="glass-panel" style={{ width: '90%', maxWidth: '1000px', height: '80vh', display: 'flex', flexDirection: 'column', border: '1px solid var(--primary-color)' }}>
                        <div style={{ padding: 'var(--spacing-md)', borderBottom: '1px solid var(--glass-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(16, 185, 129, 0.1)' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                <div style={{ width: '12px', height: '12px', background: '#f87171', borderRadius: '50%' }}></div>
                                <div style={{ width: '12px', height: '12px', background: '#fbbf24', borderRadius: '50%' }}></div>
                                <div style={{ width: '12px', height: '12px', background: '#34d399', borderRadius: '50%' }}></div>
                                <span style={{ marginLeft: '10px', fontWeight: '800', color: 'var(--primary-color)', letterSpacing: '1px' }}>REMEDIATION CONSOLE</span>
                            </div>
                            <button onClick={() => setIsFixing(false)} style={{ background: 'none', border: 'none', color: 'white', fontSize: '1.5rem', cursor: 'pointer' }}>&times;</button>
                        </div>

                        <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
                            {/* Solution Reference */}
                            <div style={{ width: '350px', borderRight: '1px solid var(--glass-border)', padding: 'var(--spacing-lg)', background: 'rgba(15, 23, 42, 0.4)', overflowY: 'auto' }}>
                                <h4 style={{ color: 'white', marginBottom: 'var(--spacing-md)' }}>Recommended Code</h4>
                                <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginBottom: 'var(--spacing-lg)' }}>Copy the solution below and paste it into the editor to resolve the threat.</p>

                                {Object.entries(pqcSolutions).map(([name, sol]) => (
                                    <div key={name} style={{ marginBottom: 'var(--spacing-xl)' }}>
                                        <div style={{ color: 'var(--primary-color)', fontWeight: '800', fontSize: '0.8rem', textTransform: 'uppercase', marginBottom: '8px' }}>{name}</div>
                                        <div style={{ background: '#0f172a', padding: '12px', borderRadius: '8px', border: '1px solid #1e293b' }}>
                                            <code style={{ fontSize: '0.75rem', color: '#34d399', whiteSpace: 'pre-wrap' }}>{sol.usage}</code>
                                            <button
                                                onClick={() => navigator.clipboard.writeText(sol.usage)}
                                                style={{ marginTop: '10px', width: '100%', padding: '6px', fontSize: '0.7rem', background: 'rgba(255,255,255,0.1)', border: 'none', color: 'white', borderRadius: '4px', cursor: 'pointer' }}
                                            >Copy Logic</button>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Live Editor */}
                            <div style={{ flex: 1, position: 'relative', display: 'flex', flexDirection: 'column' }}>
                                <div style={{ padding: '10px 20px', background: '#1e293b', fontSize: '0.75rem', color: '#94a3b8', fontWeight: '700' }}>main.js - LIVE PATCHING</div>
                                <textarea
                                    value={currentCode}
                                    onChange={(e) => setCurrentCode(e.target.value)}
                                    style={{
                                        flex: 1,
                                        background: '#0f172a',
                                        color: '#f8fafc',
                                        padding: '20px',
                                        fontFamily: 'var(--font-mono)',
                                        fontSize: '0.9rem',
                                        border: 'none',
                                        outline: 'none',
                                        resize: 'none',
                                        lineHeight: '1.6'
                                    }}
                                    placeholder="Paste your fixed code here..."
                                />
                                {data.threats === 0 && (
                                    <div style={{ position: 'absolute', bottom: '20px', left: '20px', right: '20px', background: 'rgba(16, 185, 129, 0.9)', color: 'white', padding: '15px', borderRadius: '8px', textAlign: 'center', fontWeight: '800', backdropFilter: 'blur(10px)', boxShadow: '0 10px 30px rgba(16, 185, 129, 0.3)' }} className="animate-fade-in">
                                        ✨ ALL THREATS CLEARED! Code Is Now Post-Quantum Ready.
                                    </div>
                                )}
                            </div>
                        </div>

                        <div style={{ padding: 'var(--spacing-md)', borderTop: '1px solid var(--glass-border)', display: 'flex', justifyContent: 'flex-end', gap: '15px' }}>
                            <button className="btn btn-secondary" onClick={() => setIsFixing(false)}>Discard Samples</button>
                            <button className="btn btn-primary" onClick={() => setIsFixing(false)}>Verify & Save Migration</button>
                        </div>
                    </div>
                </div>
            )}

            {/* Existing Code Inspector Modal */}
            {selectedVuln && (
                <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(15, 23, 42, 0.8)', backdropFilter: 'blur(8px)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
                    <div className="glass-panel animate-fade-in" style={{ maxWidth: '800px', width: '100%', padding: 'var(--spacing-xl)', position: 'relative', border: '1px solid var(--accent-danger)' }}>
                        <button onClick={() => setSelectedVuln(null)} style={{ position: 'absolute', top: '20px', right: '20px', background: 'none', border: 'none', color: 'var(--text-light)', cursor: 'pointer', fontSize: '1.5rem' }}>&times;</button>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: 'var(--spacing-md)' }}>
                            <div style={{ padding: '4px 12px', background: 'rgba(239, 68, 68, 0.1)', color: 'var(--accent-danger)', borderRadius: '4px', fontSize: '0.75rem', fontWeight: '800' }}>LINE {selectedVuln.line}</div>
                            <h2 style={{ fontSize: '1.5rem', fontWeight: '900' }}>Threat Vector: {selectedVuln.name}</h2>
                        </div>
                        <div style={{ background: '#0f172a', padding: '20px', borderRadius: '8px', color: '#94a3b8', fontFamily: 'var(--font-mono)', fontSize: '0.9rem', marginBottom: 'var(--spacing-xl)', borderLeft: '4px solid var(--accent-danger)', overflowX: 'auto' }}>
                            <code style={{ color: '#f8fafc', whiteSpace: 'pre' }}>{selectedVuln.line} | {selectedVuln.content}</code>
                        </div>
                        <div className="glass-panel" style={{ padding: 'var(--spacing-md)', background: 'rgba(16, 185, 129, 0.05)', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
                            <h4 style={{ color: 'var(--primary-color)', fontWeight: '800', fontSize: '0.85rem', textTransform: 'uppercase', marginBottom: '4px' }}>Migration Recommendation</h4>
                            <p style={{ fontWeight: '600' }}>{selectedVuln.recommendation}</p>
                        </div>
                        <button className="btn btn-primary" onClick={() => { setSelectedVuln(null); setIsFixing(true); }} style={{ marginTop: 'var(--spacing-lg)', width: '100%' }}>Launch Remediation Console</button>
                    </div>
                </div>
            )}

            <div className="animate-fade-in">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 'var(--spacing-xl)' }}>
                    <div>
                        <h1 style={{ fontSize: '2.25rem', fontWeight: '900', color: 'var(--text-primary)', marginBottom: '4px' }}>Security Analysis Report</h1>
                        <p style={{ color: 'var(--text-secondary)', fontWeight: '500' }}>Status: {data.threats === 0 ? <span style={{ color: 'var(--primary-color)' }}>SECURE</span> : <span style={{ color: 'var(--accent-danger)' }}>VULNERABLE</span>}</p>
                    </div>
                    <div style={{ display: 'flex', gap: 'var(--spacing-sm)' }}>
                        <button className="btn btn-secondary" onClick={handleDownload}>Export Audit Report</button>
                        <button className="btn btn-primary" onClick={onReset}>New Scan</button>
                    </div>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 'var(--spacing-md)', marginBottom: 'var(--spacing-lg)' }}>
                    <div className="glass-panel" style={{ padding: 'var(--spacing-lg)', borderTop: `4px solid ${riskColor}` }}>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', fontWeight: '800', textTransform: 'uppercase', marginBottom: 'var(--spacing-sm)' }}>Risk Score</p>
                        <h2 style={{ fontSize: '2.5rem', fontWeight: '900', color: riskColor }}>{data.riskScore}%</h2>
                    </div>
                    <div className="glass-panel" style={{ padding: 'var(--spacing-lg)', borderTop: '4px solid var(--accent-purple)' }}>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', fontWeight: '800', textTransform: 'uppercase', marginBottom: 'var(--spacing-sm)' }}>Readiness</p>
                        <h2 style={{ fontSize: '2.5rem', fontWeight: '900', color: 'var(--accent-purple)' }}>{data.readinessScore}%</h2>
                    </div>
                    <div className="glass-panel" style={{ padding: 'var(--spacing-lg)' }}>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', fontWeight: '800', textTransform: 'uppercase', marginBottom: 'var(--spacing-sm)' }}>Threat Vectors</p>
                        <h2 style={{ fontSize: '2.5rem', fontWeight: '900' }}>{data.threats}</h2>
                    </div>
                    <div className="glass-panel" style={{ padding: 'var(--spacing-lg)' }}>
                        <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', fontWeight: '800', textTransform: 'uppercase', marginBottom: 'var(--spacing-sm)' }}>Mitigation Time</p>
                        <h2 style={{ fontSize: '2.5rem', fontWeight: '900' }}>{data.mitigationTime}m</h2>
                    </div>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr 1fr', gap: 'var(--spacing-md)' }}>
                    <div className="glass-panel" style={{ padding: 'var(--spacing-xl)' }}>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '800', marginBottom: 'var(--spacing-lg)' }}>Vulnerable Algorithms</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-sm)' }}>
                            {data.vulnerable.map((alg, i) => (
                                <div key={i} onClick={() => alg.line !== '-' && setSelectedVuln(alg)} style={{ padding: '1rem', background: 'rgba(239, 68, 68, 0.05)', borderRadius: 'var(--radius-sm)', border: '1px solid rgba(239, 68, 68, 0.1)', cursor: alg.line !== '-' ? 'pointer' : 'default', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                    <div style={{ display: 'flex', flexDirection: 'column' }}>
                                        <span style={{ fontWeight: '700', color: 'var(--accent-danger)' }}>{alg.name}</span>
                                        {alg.line !== '-' && <span style={{ fontSize: '0.7rem' }}>Line {alg.line}</span>}
                                    </div>
                                    <span style={{ fontSize: '0.7rem', fontWeight: '800', background: 'var(--accent-danger)', color: 'white', padding: '2px 8px', borderRadius: '4px' }}>INSPECT</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="glass-panel" style={{ padding: 'var(--spacing-xl)' }}>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '800', marginBottom: 'var(--spacing-lg)' }}>PQC Solutions</h3>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-sm)' }}>
                            {Object.entries(pqcSolutions).map(([name, sol]) => (
                                <div key={name} style={{ padding: '1rem', background: 'rgba(16, 185, 129, 0.05)', borderRadius: 'var(--radius-sm)', border: '1px solid rgba(16, 185, 129, 0.1)', cursor: 'pointer' }} onClick={() => setIsFixing(true)}>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                        <div style={{ fontWeight: '700', color: 'var(--accent-success)' }}>{name}</div>
                                        <span style={{ fontSize: '0.6rem', padding: '2px 6px', background: 'var(--primary-color)', color: 'white', borderRadius: '4px', fontWeight: '900' }}>VIEW CODE</span>
                                    </div>
                                    <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>{sol.desc}</div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="glass-panel" style={{ padding: 'var(--spacing-xl)' }}>
                        <h3 style={{ fontSize: '1.25rem', fontWeight: '800', marginBottom: 'var(--spacing-lg)' }}>Performance Overhead</h3>
                        <div style={{ height: '150px', display: 'flex', alignItems: 'flex-end', justifyContent: 'space-around', gap: '12px' }}>
                            {[
                                { h: '30%', label: 'Classic', color: 'var(--bg-accent)' },
                                { h: '95%', label: 'Kyber', color: 'var(--primary-color)' },
                                { h: '75%', label: 'Dilith.', color: 'var(--accent-purple)' }
                            ].map((bar, i) => (
                                <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100%', justifyContent: 'flex-end' }}>
                                    <div style={{ height: bar.h, background: bar.color, borderRadius: '4px 4px 0 0' }}></div>
                                    <span style={{ fontSize: '0.65rem', textAlign: 'center', marginTop: '8px', fontWeight: '800' }}>{bar.label}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Dashboard;
